language: julia
julia:
    - 0.4.2
    - nightly
notifications:
  slack: phoenixmachina:tUJkltUznVKfynIB7gxtKHbH
services:
    - mysql
before_script:
  - mysql -u root -e 'create database dataTest;'
after_success:
- julia -e 'cd(Pkg.dir("SapphireORM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
